# Generated by Django 5.0.4 on 2024-06-07 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_cartitems_item_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart_id', 'item_name')},
        ),
    ]
