# Generated by Django 5.0.4 on 2024-06-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_cartitems_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
